# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Duane Edwards
tagline:	'blog'
description:	'My personal blog.'
url:		http://blog.duaneedwards.net

author:
  name:		'Duane Edwards'
  url:		https://plus.google.com/114207918397082076550

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/duane_edwards
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/duaneedwards
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/114207918397082076550
    desc:	Add me on google+

  - icon:	feed
    url:	http://blog.duaneedwards.net/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Duane Edwards
  url:		http://blog.duaneedwards.net
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
prose:
  rooturl: '_posts'
  siteurl: 'http://blog.duaneedwards.net/'
  relativeLinks: 'http://blog.duaneedwards.net/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
